/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Materias;

import Controlador.Coordinador;
import Modelo.Materia.MateriaVo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EliminarMateria extends javax.swing.JPanel {

    /**
     * Creates new form ini
     */
    Coordinador coordinador;
    String codigo;
    DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Codigo", "Nombre", "Tipo", "Carrera"};

    public EliminarMateria(Coordinador coord) {
        initComponents();
        coordinador = coord;
        actualizarTabla();
        offCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblReloj = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtCreditos = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        comboNivel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboCarrera = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELIMINACIÓN DE MATERIAS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1380, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Creditos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 770, 220));

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 360, -1));

        txtCodigo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 210, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 240, -1));

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 210, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 240, -1));

        comboTipoBusqueda.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre" }));
        add(comboTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 80, 20));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Créditos:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 240, -1));

        txtCreditos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditosKeyTyped(evt);
            }
        });
        add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 70, -1));

        btnBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 100, 30));

        btnEliminar.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 100, 30));

        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 30));

        comboTipo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humanística", "Básica", "Profesional" }));
        add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 210, -1));

        comboNivel.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        add(comboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 50, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nivel:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 240, -1));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Carrera:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 240, -1));

        comboCarrera.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Electricidad", "Electrónica", "Gastronomía", "Administración", "Diseño Gráfico", "Hotelería y Turismo" }));
        add(comboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinBase.png"))); // NOI18N
        jLabel1.setText(".");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFonfoRumi.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditosKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCreditosKeyTyped

    public void actualizarTabla() {
        ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
        materias = coordinador.materiasRegistradas();
        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < materias.size(); i++) {
            String arr[] = {materias.get(i).getCodigo(), materias.get(i).getNombre(), materias.get(i).getTipo(), materias.get(i).getCarrera()};
            md.addRow(arr);
        }
    }

    public boolean validaCampos() {
        if (txtCodigo.getText().equals("")) {
            return false;
        }
        if (txtCreditos.getText().equals("")) {
            return false;
        }
        if (txtNombre.getText().equals("")) {
            return false;
        }
        return true;
    }

    private void cargaTxt(MateriaVo materia) {
        txtCreditos.setText(String.valueOf(materia.getCreditos()));
        txtNombre.setText(materia.getNombre());
        comboTipo.setSelectedItem(materia.getTipo());
        comboCarrera.setSelectedItem(materia.getCarrera());
        comboNivel.setSelectedItem(String.valueOf(materia.getNivel()));
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (comboTipoBusqueda.getSelectedItem().equals("Código")) {
            String tipoB = "CODIGOMATERIA";
            String valor = txtCodigo.getText();
            MateriaVo materia = coordinador.buscarMateria(tipoB, valor);
            if (materia == null) {
                return;
            }
            cargaTxt(materia);
            codigo = materia.getCodigo();
            onCampos();
            return;
        }
        String tipoB = "NOMBREMATERIA";
        String valor = txtCodigo.getText();
        MateriaVo materia = coordinador.buscarMateria(tipoB, valor);
        if (materia == null) {
            return;
        }
        cargaTxt(materia);
        onCampos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if (resp == 0) {
            coordinador.eliminarMateria(codigo);
            limpiar();
            offCampos();
            actualizarTabla();
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        offCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void actualizarTablaCoincidencias(ArrayList<MateriaVo> materias) {

        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < materias.size(); i++) {
            String arr[] = {materias.get(i).getCodigo(), materias.get(i).getNombre(), materias.get(i).getTipo(), materias.get(i).getCarrera()};
            md.addRow(arr);
        }
    }
    
    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if (comboTipoBusqueda.getSelectedItem().equals("Código")) {
            String tipoB = "CODIGOMATERIA";
            String valor = txtCodigo.getText();
            ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
            materias = coordinador.buscarMateriasCoincidencias(tipoB, valor);
            actualizarTablaCoincidencias(materias);
            return;
        }
        String tipoB = "NOMBREMATERIA";
        String valor = txtCodigo.getText();
        ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
        materias = coordinador.buscarMateriasCoincidencias(tipoB, valor);
        actualizarTablaCoincidencias(materias);
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseEntered

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

            int fila = tabla.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            txtCodigo.setText(String.valueOf(tabla.getValueAt(fila, 0)));
        }
        comboTipoBusqueda.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    public void offCampos() {
        txtCreditos.setEnabled(false);
        txtNombre.setEnabled(false);
        comboTipo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnBuscar.setEnabled(true);
        comboNivel.setEnabled(false);
        comboCarrera.setEnabled(false);
    }

    public void onCampos() {
        btnEliminar.setEnabled(true);
        btnBuscar.setEnabled(false);
    }

    public void limpiar() {
        txtCodigo.setText("");
        txtCreditos.setText("");
        txtNombre.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboCarrera;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
