/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Materias;

import Controlador.Coordinador;
import Modelo.Materia.MateriaVo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDWIN
 */
public class IngresarMateria extends javax.swing.JPanel {

    /**
     * Creates new form ini
     */
    Coordinador coordinador;
    DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Codigo", "Nombre", "Tipo", "Carrera"};

    public IngresarMateria(Coordinador coord) {
        initComponents();
        coordinador = coord;
        actualizarTabla();
    }

    public void actualizarTabla() {
        ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
        materias = coordinador.materiasRegistradas();
        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < materias.size(); i++) {
            String arr[] = {materias.get(i).getCodigo(), materias.get(i).getNombre(), materias.get(i).getTipo(), materias.get(i).getCarrera()};
            md.addRow(arr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblReloj = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCreditos = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        comboNivel = new javax.swing.JComboBox<>();
        comboCarrera = new javax.swing.JComboBox<>();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESO DE MATERIAS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, -1));

        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 80, 30));

        btnGuardar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 80, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Creditos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 770, 220));

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 360, -1));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nombre:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 240, -1));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Tipo:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 240, -1));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Créditos:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 240, -1));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Nivel:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 240, -1));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Carrera:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 240, -1));

        txtCodigo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 210, -1));

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 210, -1));

        txtCreditos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditosKeyTyped(evt);
            }
        });
        add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 70, -1));

        comboTipo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humanística", "Básica", "Profesional" }));
        add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 210, -1));

        comboNivel.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        add(comboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 50, -1));

        comboCarrera.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Electricidad", "Electrónica", "Gastronomía", "Administración", "Diseño Gráfico", "Hotelería y Turismo" }));
        add(comboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 210, -1));

        comboTipoBusqueda.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre" }));
        add(comboTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinBase.png"))); // NOI18N
        jLabel1.setText(".");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFonfoRumi.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, 180));
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar() {
        txtCodigo.setText("");
        txtCreditos.setText("");
        txtNombre.setText("");
        comboTipo.setSelectedIndex(0);
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public boolean validaCampos() {
        if (txtCodigo.getText().equals("")) {
            return false;
        }
        if (txtCreditos.getText().equals("")) {
            return false;
        }
        if (txtNombre.getText().equals("")) {
            return false;
        }
        return true;
    }

    public void actualizarTablaCoincidencias(ArrayList<MateriaVo> materias) {

        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < materias.size(); i++) {
            String arr[] = {materias.get(i).getCodigo(), materias.get(i).getNombre(), materias.get(i).getTipo(), materias.get(i).getCarrera()};
            md.addRow(arr);
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validaCampos()) {
            String codigo = txtCodigo.getText().toUpperCase();
            String nombre = txtNombre.getText().toUpperCase();
            String creditos = txtCreditos.getText().toUpperCase();
            String tipo = (String) (comboTipo.getSelectedItem());
            String carrera = (String) (comboCarrera.getSelectedItem());
            int nivel = Integer.parseInt((String) (comboNivel.getSelectedItem()));
            if (!coordinador.existeMateria("CODIGOMATERIA", codigo) && !coordinador.existeMateria("NOMBREMATERIA", nombre)) {
                MateriaVo materia = new MateriaVo(codigo, nombre, tipo, Integer.parseInt(creditos), nivel, carrera);
                coordinador.ingresarMateria(materia);
                limpiar();
                actualizarTabla();
                return;
            }
            JOptionPane.showMessageDialog(null, "La materia ya se encuentra registrada en el sistema.", "Error de Registro", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "LLene todos los campos e inténte de nuevo", "Campos sin llenar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if (comboTipoBusqueda.getSelectedItem().equals("Código")) {
            String tipoB = "CODIGOMATERIA";
            String valor = txtCodigo.getText();
            ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
            materias = coordinador.buscarMateriasCoincidencias(tipoB, valor);
            actualizarTablaCoincidencias(materias);
            return;
        }
        String tipoB = "NOMBREMATERIA";
        String valor = txtCodigo.getText();
        ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();
        materias = coordinador.buscarMateriasCoincidencias(tipoB, valor);
        actualizarTablaCoincidencias(materias);
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditosKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCreditosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboCarrera;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
