/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Docente;

import Vista.Estudiante.*;
import Controlador.Coordinador;
import Modelo.Docente.DocenteVo;
import Modelo.Estudiante.EstudianteVo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class EliminarDocente extends javax.swing.JPanel {

    /**
     * Creates new form ini
     */
    Coordinador coordinador;
    DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Cedula", "Nombre", "Apellido", "Carga Horaria"};

    public EliminarDocente(Coordinador coord) {
        initComponents();
        offCampos();
        coordinador = coord;
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCreditos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELIMINACIÓN DE DOCENTES");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, -1));

        txtCedula.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 270, -1));

        txtNombres.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 270, -1));

        txtCreditos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditosKeyTyped(evt);
            }
        });
        add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 70, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Creditos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 770, 190));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TELFS: 2331-599 / 2332-554 / 2331-628");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 260, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("E-mail: info@ister.edu.ec");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 200, -1));

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 360, -1));

        txtApellidos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 270, -1));

        fecha.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 270, 20));

        txtTelefono.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 270, -1));

        txtEmail.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 270, -1));

        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 90, 30));

        btnEditar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnEditar.setText("ELIMINAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 90, 30));

        btnBuscar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinBase.png"))); // NOI18N
        jLabel1.setText(".");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFonfoRumi.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, 180));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cédula:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 240, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nombres:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 240, -1));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Apellidos:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 240, -1));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha de Nacimiento:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 240, -1));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Teléfono:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 240, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("e-mail:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 240, -1));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Carga Horaria:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void offCampos() {
        txtApellidos.setEnabled(false);
        txtCreditos.setEnabled(false);
        txtEmail.setEnabled(false);
        txtNombres.setEnabled(false);
        txtTelefono.setEnabled(false);
        fecha.setEnabled(false);
        txtCedula.setEnabled(true);
        btnEditar.setEnabled(false);
        btnBuscar.setEnabled(true);
    }

    public void limpiar() {
        txtApellidos.setText("");
        txtCedula.setText("");
        txtCreditos.setText("");
        txtEmail.setText("");
        txtNombres.setText("");
        txtTelefono.setText("");
        fecha.setDate(null);
    }

    public void actualizarTablaCoincidencias(ArrayList<DocenteVo> docentes) {

        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < docentes.size(); i++) {
            String arr[] = {docentes.get(i).getCedula(), docentes.get(i).getNombre1(), docentes.get(i).getApellido1(), String.valueOf(docentes.get(i).getCreditos())};
            md.addRow(arr);
        }
    }

    private void txtCreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditosKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCreditosKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        offCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if (resp == 0) {
            coordinador.eliminarDocente(txtCedula.getText());
            actualizarTabla();
            limpiar();
            offCampos();
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void cargaTxt(DocenteVo docente) {
        txtCedula.setText(docente.getCedula());
        txtNombres.setText(docente.getNombre1() + " " + docente.getNombre2());
        txtApellidos.setText(docente.getApellido1() + " " + docente.getApellido2());
        fecha.setDate(docente.getFecha());
        txtEmail.setText(docente.getMail());
        txtTelefono.setText(docente.getTelefono());
        txtCreditos.setText(String.valueOf(docente.getCreditos()));
    }

    public void actualizarTabla() {
        ArrayList<DocenteVo> docentes = new ArrayList<DocenteVo>();
        docentes = coordinador.docentesRegistrados();
        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tabla.setModel(md);
        for (int i = 0; i < docentes.size(); i++) {
            String arr[] = {docentes.get(i).getCedula(), docentes.get(i).getNombre1(), docentes.get(i).getApellido1(), String.valueOf(docentes.get(i).getCreditos())};
            md.addRow(arr);
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            DocenteVo docente = coordinador.buscarDocente(txtCedula.getText());
            if (docente == null) {
                return;
            }
            cargaTxt(docente);
            onCampos();
        } catch (IOException ex) {
            Logger.getLogger(EliminarDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        String valor = txtCedula.getText();
        ArrayList<DocenteVo> docente = new ArrayList<DocenteVo>();
        docente = coordinador.docentesCoincidencia(valor);
        actualizarTablaCoincidencias(docente);
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked


            int fila = tabla.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            txtCedula.setText(String.valueOf(tabla.getValueAt(fila, 0)));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    public void onCampos() {
        btnBuscar.setEnabled(false);
        txtCedula.setEnabled(false);
        btnEditar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
