/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PanelEstudiante;

import Vista.Estudiante.*;
import Controlador.Coordinador;
import Modelo.Estudiante.EstudianteVo;
import Modelo.Materia.MateriaVo;
import Vista.VentanaFoto;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDWIN
 */
public class EditarEstudiantePanel extends javax.swing.JPanel {

    /**
     * Creates new form ini
     */
    Coordinador coordinador;
    DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Cedula", "Nombre", "Apellido", "Carrera", "Creditos"};

    public EditarEstudiantePanel(Coordinador coord) {
        initComponents();
        coordinador = coord;
        txtCedula.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        comboCarrera = new javax.swing.JComboBox<>();
        txtCreditos = new javax.swing.JTextField();
        lblReloj = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDICIÓN DEL PERFIL DEL ESTUDIANTE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1380, -1));

        txtCedula.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 270, -1));

        txtNombres.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 270, -1));

        comboCarrera.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Electrónica", "Electricidad", "Gastronomía", "Turismo", "Diseño Gráfico", "Administración" }));
        add(comboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 160, -1));

        txtCreditos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditosKeyTyped(evt);
            }
        });
        add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 70, -1));

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 360, -1));

        txtApellidos.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 270, -1));

        fecha.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 270, 20));

        txtTelefono.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 270, -1));

        txtEmail.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 270, -1));

        btnEditar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 90, 30));

        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setText("IMAGEN");
        labelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 170, 140));

        btnCargar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 170, -1));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Contraseña:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 240, 20));

        txtPass.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 290, 20));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Confirmar Contraseña:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 210, 20));

        txtPass1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 290, 20));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Cédula:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 240, -1));

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Nombres:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 240, -1));

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Apellidos:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 240, -1));

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Carrera:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 240, -1));

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Fecha de Nacimiento:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 240, -1));

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Teléfono:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 240, -1));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("e-mail:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 240, -1));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Créditos:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinBase.png"))); // NOI18N
        jLabel1.setText(".");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFonfoRumi.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, 180));
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaCampos() {
        if (txtCedula.getText().equals("")) {
            return false;
        }
        if (txtCreditos.getText().equals("")) {
            return false;
        }
        if (txtNombres.getText().equals("")) {
            return false;
        }
        if (txtApellidos.getText().equals("")) {
            return false;
        }
        if (txtTelefono.getText().equals("")) {
            return false;
        }
        if (txtEmail.getText().equals("")) {
            return false;
        }
        if (txtPass.getText().equals("")) {
            return false;
        }
        if (txtPass1.getText().equals("")) {
            return false;
        }
        if (fecha.getDate() == null) {
            return false;
        }
        return true;
    }

    private void txtCreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditosKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCreditosKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (validaCampos()) {
            String cedula = txtCedula.getText();
            String pass = txtPass.getText();
            String[] nombres = txtNombres.getText().split(" ");
            if (nombres.length != 2) {
                JOptionPane.showMessageDialog(null, "Ingrese los dos nombres e intente de nuevo.", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String[] apellidos = txtApellidos.getText().split(" ");
            if (apellidos.length != 2) {
                JOptionPane.showMessageDialog(null, "Ingrese los dos apellidos e intente de nuevo.", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!txtPass1.getText().equals(txtPass.getText())) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden. Intente de nuevo", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
            if (resp == 0) {
                String carrera = (String) comboCarrera.getSelectedItem();
                Date date = fecha.getDate();
                String telefono = txtTelefono.getText();
                String mail = txtEmail.getText();
                int creditos = Integer.parseInt(txtCreditos.getText());
                int creditos1 = Integer.parseInt(txtCreditos.getText());

                EstudianteVo estudiante = new EstudianteVo(carrera.toUpperCase(), cedula, nombres[0].toUpperCase(), nombres[1].toUpperCase(), apellidos[0].toUpperCase(), apellidos[1].toUpperCase(), telefono, mail, pass, creditos, creditos1, date, fichero);
                coordinador.editarEstudiante(estudiante);
                coordinador.setEstudianteVo(estudiante);
            }
            return;
        } else {
            JOptionPane.showMessageDialog(null, "LLene todos los campos e inténte de nuevo", "Campos sin llenar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    public void cargaTxt() {
        EstudianteVo estudiante = new EstudianteVo();
        estudiante = coordinador.getEstudianteVo();
        txtCedula.setText(estudiante.getCedula());
        txtNombres.setText(estudiante.getNombre1() + " " + estudiante.getNombre2());
        txtApellidos.setText(estudiante.getApellido1() + " " + estudiante.getApellido2());
        comboCarrera.setSelectedItem(estudiante.getCarrera());
        fecha.setDate(estudiante.getFecha());
        txtEmail.setText(estudiante.getMail());
        txtTelefono.setText(estudiante.getTelefono());
        txtCreditos.setText(String.valueOf(estudiante.getCreditos()));
        txtPass.setText(estudiante.getPass());
        txtPass1.setText(estudiante.getPass());
        fichero = estudiante.getFoto();
        ImageIcon icon = new ImageIcon(fichero.toString());
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(170, 140, Image.SCALE_DEFAULT));
        labelFoto.setText("");
        labelFoto.setIcon(icono);
    }


    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCedulaKeyTyped

    File fichero;

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        int resultado;
        VentanaFoto foto = new VentanaFoto();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG Y PNG", "jpg", "png");
        foto.jFileChooser1.setFileFilter(filtro);
        resultado = foto.jFileChooser1.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = foto.jFileChooser1.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_DEFAULT));
                labelFoto.setText("");
                labelFoto.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen " + ex);

            }

        }
    }//GEN-LAST:event_btnCargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboCarrera;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelFoto;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
