/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PanelEstudiante;

import Controlador.Coordinador;
import Modelo.Estudiante.EstudianteVo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 
 */
public class EstudianteControl extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Dimension dim;
    Coordinador coordinador;
    EstudianteVo estudiante=new EstudianteVo();

    public EstudianteVo getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(EstudianteVo estudiante) {
        this.estudiante = estudiante;
    }
    

    public EstudianteControl(Coordinador coord) {
        coordinador = coord;
        initComponents();
        this.pack();
        dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
        //this.setUndecorated(true);
        //this.setVisible(true);
        this.getContentPane().setBackground(Color.white);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        btnInicio = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        ingresarEstudiante = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Académico Docente ISTER");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        Inicio.setText("Inicio      ");
        Inicio.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        Inicio.setMargin(new java.awt.Insets(10, 10, 10, 10));

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        Inicio.add(btnInicio);

        jMenuBar1.add(Inicio);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/manual.png"))); // NOI18N
        jMenu12.setText("Cursos      ");
        jMenu12.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jMenu12.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem26.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem26.setText("Matricularse");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem26);

        jMenuItem28.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem28.setText("Tematica");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem28);

        jMenuBar1.add(jMenu12);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientesOK.png"))); // NOI18N
        jMenu8.setText("Estudiantes      ");
        jMenu8.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jMenu8.setMargin(new java.awt.Insets(10, 10, 10, 10));

        ingresarEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ingresarEstudiante.setText("Editar");
        ingresarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarEstudianteActionPerformed(evt);
            }
        });
        jMenu8.add(ingresarEstudiante);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reservas-consumos.png"))); // NOI18N
        jMenu9.setText("Horarios      ");
        jMenu9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem20.setText("Ver");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem20);

        jMenuBar1.add(jMenu9);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application_exit.png"))); // NOI18N
        jMenu11.setText("Salir");
        jMenu11.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jMenu11.setMargin(new java.awt.Insets(10, 10, 10, 10));

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu11.add(btnCerrarSesion);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu11.add(btnSalir);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        coordinador.hideEstudianteControl();
        coordinador.showLogin();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        coordinador.showInicioDocente();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void ingresarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarEstudianteActionPerformed
        coordinador.showEditarEstudiantePanel();
    }//GEN-LAST:event_ingresarEstudianteActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
       coordinador.showMatricularEstudiante();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        coordinador.showTematicaEstudiante();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        coordinador.showHorarioEstudiante();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnInicio;
    private javax.swing.JMenuItem btnSalir;
    public javax.swing.JPanel escritorio;
    private javax.swing.JMenuItem ingresarEstudiante;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem28;
    // End of variables declaration//GEN-END:variables
}