/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class RecuperarPass extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarPass
     */
    Coordinador coordinador;

    public RecuperarPass(Coordinador coord) {
        coordinador = coord;
        this.getContentPane().setBackground(Color.white);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnMatricular = new javax.swing.JButton();
        btnMatricular1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 160, 90, 40);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RECUPERACIÓN DE CONTRASEÑA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 40);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Si los campos coinciden, enviaremos la contraseña a su correo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 40, 400, 40);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cedula: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 100, 90, 40);

        txtMail.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(txtMail);
        txtMail.setBounds(90, 160, 290, 32);

        txtCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula);
        txtCedula.setBounds(90, 100, 290, 32);

        btnMatricular.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMatricular.setText("RECUPERAR");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatricular);
        btnMatricular.setBounds(210, 220, 170, 39);

        btnMatricular1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMatricular1.setText("REGRESAR");
        btnMatricular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricular1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatricular1);
        btnMatricular1.setBounds(20, 220, 170, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        try {
            coordinador.verificaRecuperacion(txtCedula.getText().toUpperCase(), txtMail.getText().toUpperCase());
            JOptionPane.showMessageDialog(null, "Si los datos coinciden, enviaremos un mail con su contraseña", "Recuperacion de Contraseña", JOptionPane.WARNING_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(RecuperarPass.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtCedula.setText("");
        txtMail.setText("");
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void btnMatricular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricular1ActionPerformed
        coordinador.hideRecupera();
        coordinador.showLogin();
    }//GEN-LAST:event_btnMatricular1ActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCedulaKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnMatricular1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
