/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Estudiante;

import Vista.PanelEstudiante.*;
import Vista.Curso.*;
import Controlador.Coordinador;
import Modelo.Curso.ClaseVo;
import Modelo.Curso.CursoVo;
import Modelo.Docente.DocenteVo;
import Modelo.Materia.MateriaVo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class MatricularEstudianteAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ini
     */
    Coordinador coordinador;
    MateriaVo materia1 = new MateriaVo();
    DocenteVo docente1 = new DocenteVo();

    DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Curso", "Codigo Materia", "Cedula Docente"};

    DefaultTableModel md1;
    String data1[][] = {};
    String cabeza1[] = {"Codigo", "Nombre", "Tipo", "Creditos"};

    DefaultTableModel md2;
    String data2[][] = {};
    String cabeza2[] = {"Cedula", "Nombre", "Apellido", "Creditos"};

    ArrayList<DocenteVo> docentes = new ArrayList<DocenteVo>();
    ArrayList<CursoVo> cursos = new ArrayList<CursoVo>();
    ArrayList<MateriaVo> materias = new ArrayList<MateriaVo>();

    public MatricularEstudianteAdmin(Coordinador coord) {
        initComponents();
        coordinador = coord;
        actualizarTablaCursos();
        txtDocente.setEnabled(false);
        btnMatricular.setEnabled(false);

        Tcursos.setVisible(true);
        Scursos.setVisible(true);
        horario.setEnabled(false);
    }

    public void actualizarTablaCursos() {
        ArrayList<CursoVo> cursos = new ArrayList<CursoVo>();
        cursos = coordinador.cursosRegistrados();
        md = new DefaultTableModel(data, cabeza) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.Tcursos.setModel(md);
        for (int i = 0; i < cursos.size(); i++) {
            String arr[] = {String.valueOf(cursos.get(i).getCodigo()), cursos.get(i).getMateria(), cursos.get(i).getDocente()};
            md.addRow(arr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        Scursos = new javax.swing.JScrollPane();
        Tcursos = new javax.swing.JTable();
        lblReloj = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Shorario = new javax.swing.JScrollPane();
        horario = new javax.swing.JTable();
        btnVerifica = new javax.swing.JButton();
        txtDocente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATRICULACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Docente:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 190, -1));

        txtCurso.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });
        txtCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCursoKeyTyped(evt);
            }
        });
        add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 210, -1));

        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 100, 30));

        btnMatricular.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnMatricular.setText("MATRICULARSE");
        btnMatricular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        add(btnMatricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 150, 30));

        Tcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Curso", "Materia", "Cod. Materia", "Docente", "C. Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcursosMouseClicked(evt);
            }
        });
        Scursos.setViewportView(Tcursos);

        add(Scursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 770, 160));

        lblReloj.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("RELOJ");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 360, -1));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Seleccione al curso que desea matricularse:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 590, -1));

        Shorario.setBorder(null);
        Shorario.setToolTipText("");

        horario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1) 08H00 - 09H00", null, null, null, null, null},
                {"2) 09H00 - 10H00", null, null, null, null, null},
                {"3) 10H00 - 11H00", null, null, null, null, null},
                {"4) 11H00 - 12H00", null, null, null, null, null},
                {"5) 12H00 - 13H00", null, null, null, null, null},
                {"6) 13H00 - 14H00", null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Shorario.setViewportView(horario);
        if (horario.getColumnModel().getColumnCount() > 0) {
            horario.getColumnModel().getColumn(0).setResizable(false);
        }

        add(Shorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 630, 130));

        btnVerifica.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btnVerifica.setText("Validar");
        btnVerifica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaActionPerformed(evt);
            }
        });
        add(btnVerifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 80, 30));

        txtDocente.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocenteActionPerformed(evt);
            }
        });
        add(txtDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 210, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estudiante:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 190, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Curso:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 190, -1));

        txtEstudiante.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstudianteActionPerformed(evt);
            }
        });
        txtEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstudianteKeyTyped(evt);
            }
        });
        add(txtEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 210, 20));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Horario");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinBase.png"))); // NOI18N
        jLabel1.setText(".");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFonfoRumi.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    public void limpiar() {
        txtCurso.setEnabled(true);
        btnVerifica.setEnabled(true);
        btnMatricular.setEnabled(false);
        txtCurso.setText("");
        txtDocente.setText("");
        txtEstudiante.setText("");
        txtEstudiante.setEnabled(false);

    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        limpiaHorario();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        if (!coordinador.existeEstudiante(txtEstudiante.getText())) {
            JOptionPane.showMessageDialog(null, "El estudiante no se encuentra registrado en el sistema", "Registro de Estudiantes", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (coordinador.existeEstudianteMatriculado(txtEstudiante.getText(), Integer.parseInt(txtCurso.getText()))) {
            return;
        }
        
        ArrayList<ClaseVo> clases1=new ArrayList<ClaseVo>();
        ArrayList<ClaseVo> clases2=new ArrayList<ClaseVo>();
        clases2=coordinador.horarioEstudiante(txtEstudiante.getText());
        clases1=coordinador.horarioCurso(Integer.parseInt(txtCurso.getText()));
        for(int i=0; i<clases1.size(); i++){
            for(int j=0; j<clases2.size(); j++){
                if(clases1.get(i).getDia()==clases2.get(j).getDia() && clases1.get(i).getHora()==clases2.get(j).getHora()){
                    JOptionPane.showMessageDialog(null, "El estudiante ya tiene asignado una clase en este dia y esta hora");
                    return;
                }
            }
        }
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if (resp == 0) {
            coordinador.matriculaEstudiante(Integer.parseInt(txtCurso.getText()), txtEstudiante.getText());
            limpiar();
            limpiaHorario();
        }
    }//GEN-LAST:event_btnMatricularActionPerformed

    public void limpiaHorario() {
        for (int i = 0; i < 6; i++) {
            for (int j = 1; j < 6; j++) {
                horario.setValueAt("", i, j);
            }
        }
    }

    public void llenaHorario() {
        ArrayList<ClaseVo> clases = new ArrayList<ClaseVo>();
        clases = coordinador.horarioCurso(Integer.parseInt(txtCurso.getText()));
        for (int i = 0; i < 6; i++) {
            for (int j = 1; j < 6; j++) {
                for (int t = 0; t < clases.size(); t++) {
                    if (clases.get(t).getDia() == j && clases.get(t).getHora() - 1 == i) {
                        horario.setValueAt(clases.get(t).getAula(), i, j);
                    }
                }
            }
        }
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < 6; i++) {
            horario.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
    }

    private void btnVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaActionPerformed
        try {
            
       
        if (coordinador.existeCurso(Integer.parseInt(txtCurso.getText()))) {
            try {
                CursoVo curso = coordinador.buscarCurso(Integer.parseInt(txtCurso.getText()));
                DocenteVo d=coordinador.buscarDocente(curso.getDocente());
                txtDocente.setText(d.getNombre1()+" "+d.getApellido1());
                llenaHorario();
                txtCurso.setEnabled(false);
                btnMatricular.setEnabled(true);
                btnVerifica.setEnabled(false);
                txtEstudiante.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(MatricularEstudianteAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La materia no se encuentra registrada en el sistema.", "Verificacion", JOptionPane.WARNING_MESSAGE);
            btnMatricular.setEnabled(false);
        }
         } catch (Exception e) 
         {
             JOptionPane.showMessageDialog(null,"Seleccione un curso para continuar");
        }

    }//GEN-LAST:event_btnVerificaActionPerformed

    private void TcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcursosMouseClicked
        int fila = Tcursos.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            txtCurso.setText(String.valueOf(Tcursos.getValueAt(fila, 0)));
        }
    }//GEN-LAST:event_TcursosMouseClicked

    private void txtDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocenteActionPerformed

    private void txtEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstudianteActionPerformed

    private void txtEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstudianteKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtEstudianteKeyTyped

    private void txtCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCursoKeyTyped
        coordinador.logica.validaNumero(evt);
    }//GEN-LAST:event_txtCursoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scursos;
    private javax.swing.JScrollPane Shorario;
    private javax.swing.JTable Tcursos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnVerifica;
    private javax.swing.JTable horario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblReloj;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JTextField txtEstudiante;
    // End of variables declaration//GEN-END:variables
}
